require: rubocop-rails

AllCops:
    NewCops: enable
    TargetRubyVersion: 3.1.3
    SuggestExtensions: false
    Exclude:
        - 'bin/**/*'
        - 'config/puma.rb'
        - 'db/**/*'
        - 'test/**/*'

Style/FrozenStringLiteralComment:
    Enabled: false

Metrics/AbcSize:
    CountRepeatedAttributes: false

Rails/I18nLocaleTexts:
    Enabled: false